name: architect/auth
description: User management system, complete with login and registration, powered by Ory Kratos
keywords:
  - users
  - user-management
  - login
  - signup
  - ory
  - kratos
  - hydra
  - oauth
  - openid

dependencies:
  architect/smtp-server: latest
  architect/postgres: latest

parameters:
  LOG_LEVEL:
    description: One of trace, debug, info, warning, error, fatal, or panic
    default: info
  KRATOS_DB_NAME:
    description: Name of the database used to house the Kratos API contents
    default: kratos
  HYDRA_DB_NAME:
    description: Name of the database used to house the Hydra API contents
    default: hydra
  SESSION_COOKIE_NAME:
    description: Name of the cookie that stores the auth application session
    default: architect-auth
  SIGNING_SECRET:
    description: Secure key used for signing and encryption of cookies, sessions, and more
    default: 61b2946b-fd55-4d92-ba6c-6d1fa24ce4d2
  SMTP_FROM_ADDRESS:
    description: From address for outgoing triggered emails
    default: no-reply@architect.io
  GITHUB_CLIENT_ID:
    description: Client ID of a Github application that can request to act on behalf of users (does nothing unless you enable OIDC in ./kratos/.kratos.yml)
    required: false
  GITHUB_CLIENT_SECRET:
    description: Client secret of a Github application that can request to act on behalf of users (does nothing unless you enable OIDC in ./kratos/.kratos.yml)
    required: false
  LOGO_URL:
    description: URL of an image to be rendered as the logo on the authorization web pages
    default: /platform-icon.png
  APP_NAME:
    description: Name of the application users are authenticating with
    default: Architect Cloud
  THEME_PRIMARY_COLOR:
    description: A hex color to be used as the primary theme color for the application
    required: false

services:
  kratos:
    build:
      context: ./kratos/
    environment:
      KRATOS_CONFIG: file:./kratos/.kratos.yml
      LOG_LEVEL: ${{ parameters.LOG_LEVEL }}
      DEFAULT_IDENTITY_SCHEMA: file:./kratos/identity.schema.json
      GITHUB_SCHEMA_MAPPER: file:./kratos/github.schema.jsonnet
      GITLAB_SCHEMA_MAPPER: file:./kratos/gitlab.schema.jsonnet
      DSN: ${{ dependencies['architect/postgres'].interfaces.postgres.url }}/${{ parameters.KRATOS_DB_NAME }}?sslmode=disable
      PGHOST: ${{ dependencies['architect/postgres'].interfaces.postgres.host }}
      PGPORT: ${{ dependencies['architect/postgres'].interfaces.postgres.port }}
      PGUSER: ${{ dependencies['architect/postgres'].interfaces.postgres.username }}
      PGPASSWORD: ${{ dependencies['architect/postgres'].interfaces.postgres.password }}
      COURIER_SMTP_CONNECTION_URI: ${{ dependencies['architect/smtp-server'].interfaces.smtp.url }}
      COURIER_SMTP_FROM_ADDRESS: ${{ parameters.SMTP_FROM_ADDRESS }}
      SERVE_PUBLIC_BASE_URL: ${{ environment.ingresses['architect/auth'].auth.url }}
      SERVE_ADMIN_BASE_URL: ${{ services.kratos.interfaces.admin.url }}
      SELFSERVICE_WHITELISTED_RETURN_URLS: ${{ environment.ingresses['architect/auth'].auth.url }}
      SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: ${{ environment.ingresses['architect/auth'].auth.url }}
      SELFSERVICE_FLOWS_LOGIN_UI_URL: ${{ environment.ingresses['architect/auth'].auth.url }}/login
      SELFSERVICE_FLOWS_REGISTRATION_UI_URL: ${{ environment.ingresses['architect/auth'].auth.url }}/signup
      SELFSERVICE_FLOWS_VERIFICATION_UI_URL: ${{ environment.ingresses['architect/auth'].auth.url }}/verify
      SELFSERVICE_FLOWS_RECOVERY_UI_URL: ${{ environment.ingresses['architect/auth'].auth.url }}/recovery
      SELFSERVICE_FLOWS_SETTINGS_UI_URL: ${{ environment.ingresses['architect/auth'].auth.url }}/settings
      SELFSERVICE_FLOWS_ERROR_UI_URL: ${{ environment.ingresses['architect/auth'].auth.url }}/error
      SECRETS_DEFAULT: ${{ parameters.SIGNING_SECRET }}
      GITHUB_CLIENT_ID: ${{ parameters.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ parameters.GITHUB_CLIENT_SECRET }}
    interfaces:
      public: 4433
      admin: 4434
    command:
      - sh
      - -c
      - |
        echo "$DEFAULT_IDENTITY_SCHEMA" > $HOME/identity.schema.json
        echo "$GITHUB_SCHEMA_MAPPER" > $HOME/github.schema.jsonnet
        echo "$GITLAB_SCHEMA_MAPPER" > $HOME/gitlab.schema.jsonnet
        echo "$KRATOS_CONFIG" > $HOME/.kratos.yaml
        [[ -n "$GITHUB_CLIENT_ID" ]] && yq eval -i '.selfservice.methods.oidc.config.providers += {"id": "github", "provider": "github", "client_id": "strenv(GITHUB_CLIENT_ID)", "client_secret": "strenv(GITHUB_CLIENT_SECRET)", "mapper_url": "file:///home/ory/github.schema.jsonnet", "scope": ["user:email"]}' $HOME/.kratos.yaml
        sleep 5
        echo "SELECT 'CREATE DATABASE ${{ parameters.KRATOS_DB_NAME }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${{ parameters.KRATOS_DB_NAME }}')\gexec" | psql > /dev/null
        kratos migrate sql -e --yes
        kratos serve --dev

  hydra:
    build:
      context: ./hydra/
    environment:
      HYDRA_CONFIG: file:./hydra/.hydra.yml
      LOG_LEVEL: ${{ parameters.LOG_LEVEL }}
      DSN: ${{ dependencies['architect/postgres'].interfaces.postgres.url }}/${{ parameters.HYDRA_DB_NAME }}?sslmode=disable
      PGHOST: ${{ dependencies['architect/postgres'].interfaces.postgres.host }}
      PGPORT: ${{ dependencies['architect/postgres'].interfaces.postgres.port }}
      PGUSER: ${{ dependencies['architect/postgres'].interfaces.postgres.username }}
      PGPASSWORD: ${{ dependencies['architect/postgres'].interfaces.postgres.password }}
      URLS_SELF_ISSUER: ${{ environment.ingresses['architect/auth'].auth.url }}
      URLS_SELF_PUBLIC: ${{ environment.ingresses['architect/auth'].auth.url }}
      URLS_CONSENT: ${{ environment.ingresses['architect/auth'].auth.url }}/consent
      URLS_LOGIN: ${{ environment.ingresses['architect/auth'].auth.url }}/login
      URLS_LOGOUT: ${{ environment.ingresses['architect/auth'].auth.url }}/logout
      SECRETS_SYSTEM: ${{ parameters.SIGNING_SECRET }}
    interfaces:
      public: 4444
      admin: 4445
    command:
      - sh
      - -c
      - |
        echo "$HYDRA_CONFIG" > /etc/config/hydra/.hydra.yml
        sleep 5
        echo "SELECT 'CREATE DATABASE ${{ parameters.HYDRA_DB_NAME }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${{ parameters.HYDRA_DB_NAME }}')\gexec" | psql > /dev/null
        hydra migrate -c /etc/config/hydra/.hydra.yml sql -e --yes
        hydra serve -c /etc/config/hydra/.hydra.yml all --dangerous-force-http

  app:
    build:
      context: ./
    environment:
      NEXT_PUBLIC_BASE_URL: ${{ environment.ingresses['architect/auth'].auth.url }}
      LOG_LEVEL: ${{ parameters.LOG_LEVEL }}
      KRATOS_ADMIN_URL: ${{ services.kratos.interfaces.admin.url }}
      KRATOS_PUBLIC_URL: ${{ services.kratos.interfaces.public.url }}
      HYDRA_PUBLIC_URL: ${{ services.hydra.interfaces.public.url }}
      HYDRA_ADMIN_URL: ${{ services.hydra.interfaces.admin.url }}
      SIGNING_SECRET: ${{ parameters.SIGNING_SECRET }}
      SESSION_COOKIE_NAME: ${{ parameters.SESSION_COOKIE_NAME }}
      NEXT_PUBLIC_LOGO_URL: ${{ parameters.LOGO_URL }}
      NEXT_PUBLIC_APP_NAME: ${{ parameters.APP_NAME }}
      NEXT_PUBLIC_THEME_PRIMARY_COLOR: ${{ parameters.THEME_PRIMARY_COLOR }}
    interfaces:
      main: 3000
    debug:
      build:
        args:
          DEBUG: "true"
      command: npm run dev
      volumes:
        src:
          host_path: ./src/
          mount_path: /usr/src/app/src/
        public:
          host_path: ./public/
          mount_path: /usr/src/app/public/

interfaces:
  auth:
    url: ${{ services.app.interfaces.main.url }}
    description: Webapp allowing users to signup, register, and manage their profile
  hydra-admin:
    url: ${{ services.hydra.interfaces.admin.url }}
    description: Administrative API for the Hydra service (https://ory.sh/hydra/)
  kratos-admin:
    url: ${{ services.kratos.interfaces.admin.url }}
    description: Administrative API for the Kratos service (https://ory.sh/kratos/)
  mail: ${{ dependencies['architect/smtp-server'].interfaces.maildev.url }}
