name: architect/auth
description: User management system, complete with login and registration, powered by Ory Kratos and Hydra
keywords:
  - users
  - user-management
  - login
  - signup
  - ory
  - kratos
  - openid
  - oauth2

parameters:
  log_level:
    description: One of trace, debug, info, warning, error, fatal, or panic
    default: error
  kratos_db_name:
    description: Name of the database used to house the Kratos API contents
    default: kratos
  hydra_db_name:
    description: Name of the database used to house the Hydra API contents
    default: hydra
  session_cookie_name:
    description: Name of the cookie that stores the auth application session
    default: architect-auth
  signing_secret:
    description: Secure key used for signing and encryption of cookies, sessions, and more
    default: 61b2946b-fd55-4d92-ba6c-6d1fa24ce4d2
  smtp_from_address:
    description: From address for outgoing triggered emails
    default: no-reply@architect.io
  github_client_id:
    description: Client ID of a Github application that can request to act on behalf of users (does nothing unless you enable OIDC in ./kratos/.kratos.yml)
    required: 'false'
  github_client_secret:
    description: Client secret of a Github application that can request to act on behalf of users (does nothing unless you enable OIDC in ./kratos/.kratos.yml)
    required: 'false'
  logo_url:
    description: URL of an image to be rendered as the logo on the authorization web pages
    default: /platform-icon.png
  app_name:
    description: Name of the application users are authenticating with
    default: Architect Cloud
  theme_primary_color:
    description: A hex color to be used as the primary theme color for the application
    required: 'false'
  log_leak_sensitive_values:
    description: Turn on to show sensitive values in logs, like verification codes, etc.
    default: 'false'

  # Database parameters
  postgres_host:
    required: false
  postgres_user:
    default: postgres
  postgres_password:
    default: architect

  # SMTP parameters
  smtp_host:
    required: true
  smtp_port:
    required: true
  smtp_username:
    required: true
  smtp_password:
    required: true

services:
  hydra:
    depends_on:
      - auth-db
    build:
      context: ./hydra/
    environment:
      HYDRA_CONFIG: file:./hydra/.hydra.yml
      LOG_LEVEL: ${{ parameters.log_level }}
      DSN: ${{ services.auth-db.interfaces.postgres.url }}/${{ parameters.hydra_db_name }}?sslmode=disable
      URLS_SELF_ISSUER: ${{ ingresses.frontend.url }}
      URLS_SELF_PUBLIC: ${{ ingresses.frontend.url }}
      URLS_CONSENT: ${{ ingresses.frontend.url }}/oauth2/consent
      URLS_LOGIN: ${{ ingresses.frontend.url }}/oauth2/login
      URLS_LOGOUT: ${{ ingresses.frontend.url }}/oauth2/logout
      SECRETS_SYSTEM: ${{ parameters.signing_secret }}

      # Used by psql client for DB upsert
      PGHOST: ${{ services.auth-db.interfaces.postgres.host }}
      PGPORT: ${{ services.auth-db.interfaces.postgres.port }}
      PGUSER: ${{ services.auth-db.interfaces.postgres.username }}
      PGPASSWORD: ${{ services.auth-db.interfaces.postgres.password }}
    interfaces:
      public: 4444
      admin: 4445
    command:
      - sh
      - -c # TODO: fix --dangerous-force-http for remote
      - |
        echo "$HYDRA_CONFIG" > /etc/config/hydra/.hydra.yml
        sleep 5
        echo "SELECT 'CREATE DATABASE ${{ parameters.hydra_db_name }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${{ parameters.hydra_db_name }}')\gexec" | psql > /dev/null
        hydra migrate -c /etc/config/hydra/.hydra.yml sql -e --yes
        hydra serve all -c /etc/config/hydra/.hydra.yml --dangerous-force-http
    debug:
      environment:
        OAUTH2_EXPOSE_INTERNAL_ERRORS: true
        SERVE_ADMIN_CORS_DEBUG: true
        SERVE_PUBLIC_CORS_DEBUG: true
        LOG_LEVEL: info

  kratos:
    depends_on:
      - auth-db
    build:
      context: ./kratos/
    environment:
      KRATOS_CONFIG: file:./kratos/.kratos.yml
      LOG_LEVEL: ${{ parameters.log_level }}
      DEFAULT_IDENTITY_SCHEMA: file:./kratos/identity.schema.json
      GITHUB_SCHEMA_MAPPER: file:./kratos/github.schema.jsonnet
      GITLAB_SCHEMA_MAPPER: file:./kratos/gitlab.schema.jsonnet
      DSN: ${{ services.auth-db.interfaces.postgres.url }}/${{ parameters.kratos_db_name }}?sslmode=disable
      COURIER_SMTP_CONNECTION_URI: smtps://${{ parameters.smtp_username }}:${{ parameters.smtp_password }}@${{ parameters.smtp_host }}:${{ parameters.smtp_port }}
      COURIER_SMTP_FROM_ADDRESS: ${{ parameters.smtp_from_address }}
      SERVE_PUBLIC_BASE_URL: ${{ ingresses.frontend.url }}
      SERVE_ADMIN_BASE_URL: ${{ services.kratos.interfaces.admin.url }}
      SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: ${{ ingresses.frontend.url }}
      SELFSERVICE_FLOWS_LOGIN_UI_URL: ${{ ingresses.frontend.url }}/login
      SELFSERVICE_FLOWS_REGISTRATION_UI_URL: ${{ ingresses.frontend.url }}/signup
      SELFSERVICE_FLOWS_VERIFICATION_UI_URL: ${{ ingresses.frontend.url }}/verify
      SELFSERVICE_FLOWS_RECOVERY_UI_URL: ${{ ingresses.frontend.url }}/recovery
      SELFSERVICE_FLOWS_SETTINGS_UI_URL: ${{ ingresses.frontend.url }}/settings
      SELFSERVICE_FLOWS_ERROR_UI_URL: ${{ ingresses.frontend.url }}/error
      SECRETS_DEFAULT: ${{ parameters.signing_secret }}
      CONSUMERS: ${{ ingresses.frontend.consumers }}
      LOG_LEAK_SENSITIVE_VALUES: ${{ parameters.log_leak_sensitive_values }}
      GITHUB_CLIENT_ID: ${{ parameters.github_client_id }}
      GITHUB_CLIENT_SECRET: ${{ parameters.github_client_secret }}

      # Used by the psql client during startup
      PGHOST: ${{ services.auth-db.interfaces.postgres.host }}
      PGPORT: ${{ services.auth-db.interfaces.postgres.port }}
      PGUSER: ${{ services.auth-db.interfaces.postgres.username }}
      PGPASSWORD: ${{ services.auth-db.interfaces.postgres.password }}
    interfaces:
      public: 4433
      admin: 4434
    command:
      - sh
      - -c
      - |
        echo "$DEFAULT_IDENTITY_SCHEMA" > $HOME/identity.schema.json
        echo "$GITHUB_SCHEMA_MAPPER" > $HOME/github.schema.jsonnet
        echo "$GITLAB_SCHEMA_MAPPER" > $HOME/gitlab.schema.jsonnet
        echo "$KRATOS_CONFIG" > $HOME/.kratos.yaml
        [[ -n "$GITHUB_CLIENT_ID" ]] && yq eval -i '.selfservice.methods.oidc.config.providers += {"id": "github", "provider": "github", "client_id": env(GITHUB_CLIENT_ID), "client_secret": env(GITHUB_CLIENT_SECRET), "mapper_url": "file:///home/ory/github.schema.jsonnet", "scope": ["user:email"]}' $HOME/.kratos.yaml
        sleep 5
        echo "SELECT 'CREATE DATABASE ${{ parameters.kratos_db_name }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${{ parameters.kratos_db_name }}')\gexec" | psql > /dev/null
        export SELFSERVICE_WHITELISTED_RETURN_URLS=$$(jq -n --raw-output --argjson CONSUMERS "$CONSUMERS" --argjson BASE_URL "[\"$SERVE_PUBLIC_BASE_URL\"]" '$CONSUMERS + $BASE_URL | join(",")')
        kratos migrate sql -e --yes
        kratos serve -c $HOME/.kratos.yaml --watch-courier
    debug:
      environment:
        HASHERS_BCRYPT_COST: 4
        LOG_LEVEL: info
        SERVE_PUBLIC_CORS_DEBUG: true

  auth-db:
    image: postgres:11
    interfaces:
      postgres:
        host: ${{ parameters.postgres_host }}
        port: 5432
        protocol: postgres
        username: ${{ parameters.postgres_user }}
        password: ${{ parameters.postgres_password }}
    environment:
      POSTGRES_USER: ${{ parameters.postgres_user }}
      POSTGRES_PASSWORD: ${{ parameters.postgres_password }}

  app:
    build:
      context: ./
    environment:
      BASE_URL: ${{ ingresses.frontend.url }}
      LOG_LEVEL: ${{ parameters.log_level }}
      KRATOS_ADMIN_URL: ${{ services.kratos.interfaces.admin.url }}
      KRATOS_PUBLIC_URL: ${{ services.kratos.interfaces.public.url }}
      HYDRA_ADMIN_URL: ${{ services.hydra.interfaces.admin.url }}
      HYDRA_PUBLIC_URL: ${{ services.hydra.interfaces.public.url }}
      SIGNING_SECRET: ${{ parameters.signing_secret }}
      SESSION_COOKIE_NAME: ${{ parameters.session_cookie_name }}
      THEME_PRIMARY_COLOR: ${{ parameters.theme_primary_color }}
      NUXT_ENV_LOGO_URL: ${{ parameters.logo_url }}
      NUXT_ENV_APP_NAME: ${{ parameters.app_name }}
    interfaces:
      main: 3000
    debug:
      build:
        args:
          DEBUG: 'true'
      command: npm run dev
      volumes:
        src:
          host_path: ./src/
          mount_path: /app/src/

interfaces:
  frontend:
    url: ${{ services.app.interfaces.main.url }}
    description: Webapp allowing users to signup, register, and manage their profile
  kratos-admin:
    url: ${{ services.kratos.interfaces.admin.url }}
    description: Administrative endpoints for the Kratos service (https://ory.sh/kratos/)
  hydra-admin:
    url: ${{ services.hydra.interfaces.admin.url }}
    description: Administrative endpoints for the Hydra service (https://ory.sh/hydra/)
