identity:
  default_schema_url: file:///home/ory/identity.schema.json

selfservice:
  flows:
    settings:
      privileged_session_max_age: 1m
    login:
      lifespan: 10m
    verification:
      enabled: true
    registration:
      lifespan: 10m
      after:
        oidc:
          hooks:
            - hook: session
        password:
          hooks:
            - hook: session
    recovery:
      enabled: true
      lifespan: 10m
  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers: []
    link:
      enabled: true

serve:
  public:
    cors:
      enabled: true
